# Generated by Django 4.2 on 2023-04-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=100)),
                ('IIN', models.IntegerField(max_length=12)),
                ('company', models.CharField(max_length=100)),
                ('planned_start_time', models.CharField(max_length=50)),
                ('planned_finish_time', models.CharField(max_length=50)),
                ('company_branch', models.CharField(max_length=100)),
                ('real_start_time', models.CharField(max_length=50)),
                ('real_finish_time', models.CharField(max_length=50)),
                ('document_date', models.DateField()),
            ],
        ),
    ]
