# Generated by Django 4.2 on 2023-04-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('IIN', models.IntegerField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('planned_start_time', models.CharField(blank=True, max_length=50, null=True)),
                ('planned_finish_time', models.CharField(blank=True, max_length=50, null=True)),
                ('company_branch', models.CharField(blank=True, max_length=100, null=True)),
                ('real_start_time', models.CharField(blank=True, max_length=50, null=True)),
                ('real_finish_time', models.CharField(blank=True, max_length=50, null=True)),
                ('document_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
